version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region ${region} --no-include-email)
      - echo Fetching Dep for Golang dependency management...
      - go get -u github.com/golang/dep/cmd/dep
      - echo Moving project files into GOPATH...
      - mkdir -p ../github.com/dakhipp/graphql-services
      - mv * ../github.com/dakhipp/graphql-services
      - mv ../github.com .
      - cd github.com/dakhipp/graphql-services
      - echo Installing vendor dependencies...
      - dep ensure
      - echo Entering the build phase...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Starting Docker Compose...
      - docker-compose -f deployments/docker-compose/docker-compose.prod.yml up -d --build ; cd tests/integration/ ; go test ; cd ../..
      - echo Tagging images built with Docker Compose...
      - docker tag docker-compose_graphql ${graphql_repository_url}:$COMMIT_HASH
      - docker tag docker-compose_auth ${auth_repository_url}:$COMMIT_HASH
      - docker tag docker-compose_migrations ${migration_repository_url}:$COMMIT_HASH
      - if [[ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]]; then exit 1;
      - echo Build completed on `date`
  post_build:
    commands:
      - if [[ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]]; then exit 1;
      - echo Pushing the Docker images...
      - docker push ${graphql_repository_url}:$COMMIT_HASH
      - docker push ${auth_repository_url}:$COMMIT_HASH
      - docker push ${migration_repository_url}:$COMMIT_HASH
      - echo Writing image definitions file...
      - echo "[{\"name\":\"graphql\",\"imageUri\":\"${graphql_repository_url}:$COMMIT_HASH\"},{\"name\":\"auth\",\"imageUri\":\"${auth_repository_url}:$COMMIT_HASH\"}]" > $CODEBUILD_SRC_DIR/imagedefinitions.json
      - echo Running migration standalone ECS task...
      - aws ecs run-task --launch-type FARGATE --cluster ${cluster_name} --task-definition ${environment}_db_migrate --network-configuration "awsvpcConfiguration={subnets=[${subnet_id}],securityGroups=[${security_group_ids}]}"

artifacts:
  files:
    - imagedefinitions.json
