// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type RegisterArgs struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}
type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}
