version: "3.6"

services:
  graphql:
    build:
      context: "../../"
      dockerfile: "deployments/docker/graphql/prod.Dockerfile"
    ports:
      - "8000:8000"
    depends_on:
      - "auth"
    environment:
      - PORT=8000
      - PLAYGROUND=true
      - AUTH_SERVICE_URL=auth:8001
      - REDIS_URL=redis://root:toor@redis:6379/0
      - DOMAIN=localhost

  auth:
    build:
      context: "../../"
      dockerfile: "deployments/docker/auth/prod.Dockerfile"
    depends_on:
      - "psql"
    environment:
      - PORT=8001
      - PSQL_URL=postgres://root:toor@psql/psql?sslmode=disable

  migrations:
    build:
      context: "../../"
      dockerfile: "deployments/docker/migrations/prod.Dockerfile"
    depends_on:
      - "psql"
    environment:
      - PSQL_ADDR=psql:5432
      - PSQL_USER=root
      - PSQL_PASS=toor
      - PSQL_DB=psql

  redis:
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    command: >
      --requirepass toor
    restart: "unless-stopped"

  psql:
    image: postgres:10.4
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "psql"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor"
    restart: "unless-stopped"
