version: "3.6"

services:
  graphql:
    build:
      context: "../../"
      dockerfile: "deployments/docker/graphql/dev.Dockerfile"
    ports:
      - "8000:8000"
    depends_on:
      - "auth"
    volumes:
      - ../../graphql:/go/src/github.com/dakhipp/graphql-services/graphql
    environment:
      - PORT=8000
      - PLAYGROUND=true
      - AUTH_SERVICE_URL=auth:8001
      - REDIS_URL=redis://root:toor@redis:6379/0
      - DOMAIN=localhost

  auth:
    build:
      context: "../../"
      dockerfile: "deployments/docker/auth/dev.Dockerfile"
    depends_on:
      - "mongodb"
    volumes:
      - ../../auth:/go/src/github.com/dakhipp/graphql-services/auth
    environment:
      - PORT=8001
      - MONGO_URL=mongodb://user:pass@mongodb/graphql-services

  redis:
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    command: >
      --requirepass toor
    restart: "unless-stopped"

  mongodb:
    image: 'bitnami/mongodb:3.6'
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=pass
      - MONGODB_DATABASE=graphql-services
    restart: "unless-stopped"
