version: "3.6"

services:
  graphql:
    build:
      context: "../../"
      dockerfile: "deployments/docker/graphql/dev.Dockerfile"
    ports:
      - "8000:8000"
    depends_on:
      - "auth"
    volumes:
      - ../../graphql:/go/src/github.com/dakhipp/graphql-services/graphql
    environment:
      - PORT=8000
      - PLAYGROUND=true
      - AUTH_SERVICE_URL=auth:8001

  auth:
    build:
      context: "../../"
      dockerfile: "deployments/docker/auth/dev.Dockerfile"
    depends_on:
      - "psql"
    volumes:
      - ../../auth:/go/src/github.com/dakhipp/graphql-services/auth
    environment:
      - PORT=8001
      - PSQL_ADDR=psql:5432
      - PSQL_USER=root
      - PSQL_PASS=toor
      - PSQL_DB=psql
      - PSQL_SSL=disable

  psql:
    image: postgres:10.4
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "psql"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor"
    restart: "unless-stopped"
