version: "3.6"

services:
  auth:
    build:
      context: "../../"
      dockerfile: "deployments/docker/auth/prod.Dockerfile"
    depends_on:
      - "psql"
    environment:
      - PORT=8080
      - ENV=development
      - DATABASE_URL=postgres://root:toor@psql/psql?sslmode=disable

  graphql:
    build:
      context: "../../"
      dockerfile: "deployments/docker/graphql/prod.Dockerfile"
    ports:
      - "8000:8080"
    depends_on:
      - "auth"
    environment:
      - PORT=8080
      - ENV=development
      - AUTH_SERVICE_URL=auth:8080

  psql:
    build:
      context: "../../"
      dockerfile: "deployments/psql/Dockerfile"
    environment:
      POSTGRES_DB: "psql"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor"
    restart: "unless-stopped"
