version: "3.6"

services:
  graphql:
    build:
      context: "../../"
      dockerfile: "deployments/docker/graphql/prod.Dockerfile"
    ports:
      - "8000:8000"
    depends_on:
      - "auth"
    networks:
      - "appnet"
    environment:
      - PORT=8000
      - PLAYGROUND=true
      - AUTH_SERVICE_URL=localhost:8001

  auth:
    build:
      context: "../../"
      dockerfile: "deployments/docker/auth/prod.Dockerfile"
    depends_on:
      - "psql"
    networks:
      - "appnet"
    environment:
      - PORT=8001
      - PSQL_ADDR=psql:5432
      - PSQL_USER=root
      - PSQL_PASS=toor
      - PSQL_DB=psql
      - PSQL_SSL=disable

  migrations:
    build:
      context: "../../"
      dockerfile: "deployments/docker/migrations/prod.Dockerfile"
    depends_on:
      - "psql"
    networks:
      - "appnet"
    environment:
      - PSQL_ADDR=psql:5432
      - PSQL_USER=root
      - PSQL_PASS=toor
      - PSQL_DB=psql
      - PSQL_SSL=disable

  psql:
    image: postgres:10.4
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - "appnet"
    environment:
      POSTGRES_DB: "psql"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor"
    restart: "unless-stopped"

networks:
  appnet:
    driver: "bridge"
