version: "3.6"

services:
  graphql:
    build:
      context: "../../"
      dockerfile: "deployments/docker/graphql/prod.Dockerfile"
    ports:
      - "8000:8000"
    depends_on:
      - "auth"
      - "redis"
    environment:
      - PORT=8000
      - PLAYGROUND=true
      - AUTH_SERVICE_URL=auth:8001
      - REDIS_URL=redis://root:toor@redis:6379/0
      - DOMAIN=localhost

  auth:
    build:
      context: "../../"
      dockerfile: "deployments/docker/auth/prod.Dockerfile"
    depends_on:
      - "mongodb"
      - "kafka"
      - "email"
      - "text"
    environment:
      - PORT=8001
      - MONGO_URL=mongodb://user:pass@mongodb/graphql-services
      - KAFKA_ADDR=kafka:9092

  email:
    build:
      context: "../../"
      dockerfile: "deployments/docker/email/prod.Dockerfile"
    depends_on:
      - "kafka"
    volumes:
      - ../../email:/go/src/github.com/dakhipp/graphql-services/email
    environment:
      - KAFKA_BROKERS=kafka:9092
      - ENV=dev

  text:
    build:
      context: "../../"
      dockerfile: "deployments/docker/text/prod.Dockerfile"
    depends_on:
      - "kafka"
    volumes:
      - ../../text:/go/src/github.com/dakhipp/graphql-services/text
    environment:
      - KAFKA_BROKERS=kafka:9092
      - ENV=dev

  redis:
    image: 'bitnami/redis:latest'
    expose:
      - "6379"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=toor
    volumes:
      - /tmp/docker/redis:/bitnami/redis/data
    restart: "unless-stopped"

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    expose:
      - "2181"
      - "2888"
      - "3888"
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - /tmp/docker/zookeeper:/bitnami/zookeeper
    restart: "always"

  kafka:
    image: 'bitnami/kafka:latest'
    expose:
      - "9092"
    ports:
      - '9092:9092'
    depends_on:
      - "zookeeper"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181,zookeeper:2888,zookeeper:3888
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /tmp/docker/kafka:/bitnami/kafka
    restart: "always"

  mongodb:
    image: 'bitnami/mongodb:3.6'
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=pass
      - MONGODB_DATABASE=graphql-services
    volumes:
      - /tmp/docker/mongodb:/bitnami/mongodb
    restart: "unless-stopped"
